name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint for backend
        run: yarn workspace backend lint

      - name: Build the backend
        run: yarn workspace backend build

      - name: Install Render CLI
        run: curl -fsSL https://cli.render.com/install.sh | bash

      - name: Authenticate Render CLI for backend
        run: render login --api-key ${{ secrets.RENDER_API_KEY }}

      # Push Prisma Schema and Seed Data
      - name: Push Prisma Schema and Seed Data
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          yarn workspace backend prisma generate
          yarn workspace backend prisma db push
          yarn workspace backend seed

      # Deploy backend to Render
      - name: Deploy Backend to Render
        run: render deploy --service-id ${{ secrets.RENDER_SERVICE_ID }}